#  create pod 'app-secret-env' to run image 'gcr.io/k8s-k3s-387907/demo:v2.0.0' and expose port 8080, add env secret SECRET_USERNAME with secretKeyRef(name: mysecret1, key: username), add env secret SECRET_PASSWORD with secretKeyRef(name: mysecret1, key: password)
apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
spec:
  containers:
  - name: app
    image: gcr.io/k8s-k3s-387907/demo:v2.0.0
    ports:
    - containerPort: 8080
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret1
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret1
          key: password