#Create cronejob with name 'app-cronjob' to execute daily at 22:00, Create cronejob with name 'app-cronjob' to execute daily at 22:00

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule: "0 22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: bash
            command: ["echo", "Hello, world!"]
          restartPolicy: OnFailure
